interface ItemSetEntry {
    hero: string
    market_hash_name: string
}

const ITEM_SET_LIST: ItemSetEntry[] = [
   { hero: '', market_hash_name: 'Fires of Vashundol' },
    { hero: '', market_hash_name: 'Armor of the Unyielding Mask' },
    { hero: '', market_hash_name: 'Serpent of the Emerald Sea' },
    { hero: '', market_hash_name: 'Flowing Entropy' },
    { hero: '', market_hash_name: 'Echoes of the Eyrie' },
    { hero: '', market_hash_name: 'Brawler of the Glacier Sea' },
    { hero: '', market_hash_name: 'Knight of the Burning Scale' },
    { hero: '', market_hash_name: 'Garb of the Cunning Augur' },
    { hero: '', market_hash_name: 'Apostle of Decay' },
    { hero: '', market_hash_name: 'Flowersong Tempest' },
    { hero: '', market_hash_name: 'Beacon of Cerulean Light' },
    { hero: '', market_hash_name: 'The International 2015 - 11 Compendium Levels' },
    { hero: '', market_hash_name: 'Faceless Rex' },
    { hero: '', market_hash_name: 'Oni Knight the Dark Conqueror' },
    { hero: '', market_hash_name: 'Fortified Fabricator' },
    { hero: '', market_hash_name: 'Diabolical Fiend' },
    { hero: '', market_hash_name: 'Creeping Shadow' },
    { hero: '', market_hash_name: 'Stormwrought Arbiter' },
    { hero: '', market_hash_name: 'Iceburnt Elegy' },
    { hero: '', market_hash_name: 'Wartorn Heavens' },
    { hero: '', market_hash_name: 'Heir of Terror' },
    { hero: '', market_hash_name: 'Dirgeful Overlord' },
    { hero: '', market_hash_name: "Nightsilver's Resolve" },
    { hero: '', market_hash_name: 'Fractured Envoy' },
    { hero: '', market_hash_name: 'Rising Glory' },
    { hero: '', market_hash_name: 'The Family Values Bundle' },
    { hero: '', market_hash_name: 'Atrophic Skitterwing' },
    { hero: '', market_hash_name: 'Doomsday Ripper' },
    { hero: '', market_hash_name: 'Hakobi and Tenneko Bundle' },
    { hero: '', market_hash_name: 'Jolly Reaver' },
    { hero: '', market_hash_name: 'Eternal Testament' },
    { hero: '', market_hash_name: 'Secrets of the Katekhein' },
    { hero: '', market_hash_name: "Rumrunner's Carronade" },
    { hero: '', market_hash_name: 'Abyssal Vortex' },
    { hero: '', market_hash_name: 'Samareen Sacrifice' },
    { hero: '', market_hash_name: 'Seablight Procession' },
    { hero: '', market_hash_name: 'Corruption of the Virulent Krait' },
    { hero: '', market_hash_name: 'Seaborne Reprisal' },
    { hero: '', market_hash_name: 'Pressure Regulator' },
    { hero: '', market_hash_name: 'Meranth Dragoon' },
    { hero: '', market_hash_name: 'Spoils of the Vodou Rover' },
    { hero: '', market_hash_name: 'Shadowforce Gale' },
    { hero: '', market_hash_name: 'Mechalodon Interdictor' },
    { hero: '', market_hash_name: 'Riptide Raider' },
    { hero: '', market_hash_name: 'The Dread Prophet' },
    { hero: '', market_hash_name: 'Covenant of the Depths' },
    { hero: '', market_hash_name: 'Sovereign of the Kray Legions' },
    { hero: '', market_hash_name: 'Cunning Corsair' },
    { hero: '', market_hash_name: 'Chitinous Stalker' },
    { hero: '', market_hash_name: 'Submerged Hazard' },
    { hero: '', market_hash_name: 'Manta Marauder' },
    { hero: '', market_hash_name: 'Heiress of the Coastal Kingdom' },
    { hero: '', market_hash_name: 'Trail of the Sanguine Spectrum' },
    { hero: '', market_hash_name: 'Pitfall Crusader' },
    { hero: '', market_hash_name: 'Insights of the Sapphire Shroud' },
    { hero: '', market_hash_name: 'Pillar of the Fractured Citadel' },
    { hero: '', market_hash_name: 'Forlorn Descent' },
    { hero: '', market_hash_name: 'Stonemarch Sovereign' },
    { hero: '', market_hash_name: 'The Murid Divine' },
    { hero: '', market_hash_name: "Primer of the Sapper's Guile" },
    { hero: '', market_hash_name: 'Molokau Stalker' },
    { hero: '', market_hash_name: 'Morbific Provision' },
    { hero: '', market_hash_name: 'Raptures of the Abyssal Kin' },
    { hero: '', market_hash_name: 'Fate Meridian' },
    { hero: '', market_hash_name: 'Grasp of the Riven Exile' },
    { hero: '', market_hash_name: 'Visions of the Lifted Veil' },
    { hero: '', market_hash_name: 'Dread Compact' },
    { hero: '', market_hash_name: 'Endowments of the Lucent Canopy' },
    { hero: '', market_hash_name: 'Vespidun Hunter-Killer' },
    { hero: '', market_hash_name: 'Pitmouse Fraternity' },
    { hero: '', market_hash_name: 'Fires of the Volcanic Guard' },
    { hero: '', market_hash_name: 'Third Awakening' },
    { hero: '', market_hash_name: 'Shackles of the Enduring Conscript' },
    { hero: '', market_hash_name: 'Shimmer of the Anointed' },
    { hero: '', market_hash_name: 'Cruelties of the Spiral Bore' },
    { hero: '', market_hash_name: 'Loaded Prospects' },
    { hero: '', market_hash_name: 'Ire of Molten Rebirth' },
    { hero: '', market_hash_name: 'Pattern of the Silken Queen' },
    { hero: '', market_hash_name: 'Dread Ascendance' },
    { hero: '', market_hash_name: 'The Forgotten Station' },
    { hero: '', market_hash_name: 'Dirge Amplifier' },
    { hero: '', market_hash_name: 'Champion of the Fire Lotus' },
    { hero: '', market_hash_name: 'Deathstitch Shaman' },
    { hero: '', market_hash_name: 'Blue Horizons' },
    { hero: '', market_hash_name: 'Angel of Vex' },
    { hero: '', market_hash_name: 'Dark Behemoth' },
    { hero: '', market_hash_name: 'Astral Origins' },
    { hero: '', market_hash_name: 'Bird of Prey' },
    { hero: '', market_hash_name: 'Grand Suppressor' },
    { hero: '', market_hash_name: "Darkbrew's Transgression" },
    { hero: '', market_hash_name: 'Transcendent Path' },
    { hero: '', market_hash_name: 'The Wilding Tiger' },
    { hero: '', market_hash_name: 'Dawn of a Darkness Foretold' },
    { hero: '', market_hash_name: 'Cursed Cryptbreaker' },
    { hero: '', market_hash_name: 'Feasts of Forever' },
    { hero: '', market_hash_name: 'Darkfeather Factioneer' },
    { hero: '', market_hash_name: 'Withering Pain' },
    { hero: '', market_hash_name: 'Freeboot Fortunes' },
    { hero: '', market_hash_name: 'Acrimonies of Obsession' },
    { hero: '', market_hash_name: 'Sacred Chamber Guardian' },
    { hero: '', market_hash_name: 'War Rig Eradicators' },
    { hero: '', market_hash_name: 'Grudges of the Gallows Tree' },
    { hero: '', market_hash_name: 'Brands of the Reaper' },
    { hero: '', market_hash_name: 'Sublime Equilibrium' },
    { hero: '', market_hash_name: 'Unities of Discord' },
    { hero: '', market_hash_name: 'Primeval Abomination' },
    { hero: '', market_hash_name: 'Astral Herald' },
    { hero: '', market_hash_name: 'Spectral Shadow' },
    { hero: '', market_hash_name: 'Taur Rider' },
    { hero: '', market_hash_name: 'Crescent Huntress' },
    { hero: '', market_hash_name: 'Tyrant of the Veil' },
    { hero: '', market_hash_name: "Tomo'kan Footsoldier" },
    { hero: '', market_hash_name: 'Darkwood Eulogy' },
    { hero: '', market_hash_name: 'Sea Spirit' },
    { hero: '', market_hash_name: 'Triumph of the Imperatrix' },
    { hero: '', market_hash_name: 'Beast of Thunder' },
    { hero: '', market_hash_name: 'Ancestral Heritage' },
    { hero: '', market_hash_name: 'Dezun Viper' },
    { hero: '', market_hash_name: 'Brightfist' },
    { hero: '', market_hash_name: 'Snailfire' },
    { hero: '', market_hash_name: 'Turstarkuri Pilgrim' },
    { hero: '', market_hash_name: 'Darkblade Adept' },
    { hero: '', market_hash_name: "Phantom's Facade" },
    { hero: '', market_hash_name: 'Lotus of the Mountain Bear Clan' },
    { hero: '', market_hash_name: 'Martyrdom of the Brineborn' },
    { hero: '', market_hash_name: 'Elegy of the Reaper' },
    { hero: '', market_hash_name: 'Mecha Nyx' },
    { hero: '', market_hash_name: 'Faithful Fortune' },
    { hero: '', market_hash_name: 'Ardalan Arms Race' },
    { hero: '', market_hash_name: 'Dread of Night' },
    { hero: '', market_hash_name: 'Blackwing Bandolera' },
    { hero: '', market_hash_name: 'Exquisite Agonies' },
    { hero: '', market_hash_name: 'Colossal Terrorpin' },
    { hero: '', market_hash_name: 'Proselyte of the Sakura Clan' },
    { hero: '', market_hash_name: 'Bloodmoon Stalker' },
    { hero: '', market_hash_name: 'Ancient Exile' },
    { hero: '', market_hash_name: 'Aberrant Observer' },
    { hero: '', market_hash_name: 'Igneous Infernal' },
    { hero: '', market_hash_name: 'Bleeding Edge' },
    { hero: '', market_hash_name: 'Magus Mimicry' },
    { hero: '', market_hash_name: 'Seam Ripper Snuggle Time' },
    { hero: '', market_hash_name: 'Angler in the Abyss' },
    { hero: '', market_hash_name: 'Phantom Balladeer' },
    { hero: '', market_hash_name: 'Bootblack Brawler' },
    { hero: '', market_hash_name: 'Needlepoint Necromancer' },
    { hero: '', market_hash_name: 'Hare of the Cog' },
    { hero: '', market_hash_name: 'Thundervolt' },
    { hero: '', market_hash_name: 'Caprine Chimera' },
    { hero: '', market_hash_name: 'Canis Crystallum' },
    { hero: '', market_hash_name: 'Unchained Entropy' },
    { hero: '', market_hash_name: 'Undying Love' },
    { hero: '', market_hash_name: 'Crystal Colossus' },
    { hero: '', market_hash_name: 'Secondhand Sorcery' },
    { hero: '', market_hash_name: 'Glutton of Punishment' },
    { hero: '', market_hash_name: 'Lord of the Sundered Souls' },
    { hero: '', market_hash_name: 'Prehistoric Predator' },
    { hero: '', market_hash_name: 'Insantiable Seas' },
    { hero: '', market_hash_name: 'White Widow' },
    { hero: '', market_hash_name: 'Angel of the Abyss' },
    { hero: '', market_hash_name: 'Blinding Bastion' },
    { hero: '', market_hash_name: 'Harrow’s Harvest' },
    { hero: '', market_hash_name: 'Seed of Strife' },
    { hero: '', market_hash_name: 'Laurels of the Dawnstar' },
    { hero: '', market_hash_name: 'Sodbustin’ Saboteurs' },
    { hero: '', market_hash_name: 'Sins of the Simian Sovereign' },
    { hero: '', market_hash_name: 'Worship of the Whispered Wing' },
    { hero: '', market_hash_name: 'Cunning Counterfelt' },
    { hero: '', market_hash_name: 'Fluid Frenzy' },
    { hero: '', market_hash_name: 'Stone Giant Stronghold' }
]

export const ITEM_SET_ALLOWLIST = new Set(ITEM_SET_LIST.map((i) => i.market_hash_name))

const ITEM_SET_HERO_MAP = new Map(
    ITEM_SET_LIST.map((i) => [i.market_hash_name, i.hero || null]),
)

export function getItemHeroName(marketHashName: string): string | null {
    return ITEM_SET_HERO_MAP.get(marketHashName) ?? null
}

export function getItemHeroSlug(marketHashName: string): string | null {
    const name = getItemHeroName(marketHashName)
    if (!name) return null
    return name.toLowerCase().replace(/\s+/g, '_').replace(/[^a-z0-9_]/g, '')
}
